notifications:
    slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
    email: false
  
  sudo: false
  
  services:
    - docker
  
  script:
   - set -e
   - echo 'Build and check docker image'
   - docker build -t crisprreadcounts .
   - docker images | grep -c crisprreadcounts
   # verify the perl script installation
   - docker run -t --rm crisprreadcounts crisprReadCounts --version
   - docker run -t --rm crisprreadcounts crisprReadCounts count-single --help
   - docker run -t --rm crisprreadcounts crisprReadCounts count-dual --help
   - docker run -t --rm crisprreadcounts crisprReadCounts merge-single --help
